# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
imports_granularity = "Crate"
# format_code_in_doc_comments = true
comment_width = 100
# wrap_comments = true
format_macro_matchers = true
format_strings = true
