vim.g.everforest_background = "hard"
vim.g.everforest_cursor = "blue"
vim.g.everforest_enable_italic = 1
vim.g.everforest_transparent_background = 1
vim.g.everforest_ui_contrast = "low"
vim.g.everforest_diagnostic_text_highlight = 1
vim.g.everforest_diagnostic_line_highlight = 1
vim.g.everforest_diagnostic_virtual_text = "colored"
-- vim.cmd([[colorscheme everforest]])
