[plugins."balance-theme.nvim"]
git = "dericktseng/balance-theme.nvim"
rev = "fd4edfc4767166d862b82814dcd8e231fb2b03c5"
branch = "master"

[plugins."bamboo.nvim"]
git = "ribru17/bamboo.nvim"
rev = "97124a0b81f886abc0d666ebec512b92425d67b6"
branch = "master"

# Dark: nice and green/red.
# Light: so flat, it's unusable.
[plugins."caret.nvim"]
git = "projekt0n/caret.nvim"
rev = "v1.0.0"

[plugins."deepwhite.nvim"]
git = "verf/deepwhite.nvim"
rev = "ccad56bb5eb7d29258980cfc0a716eb87bcad69e"
branch = "main"

[plugins."everforest-nvim"]
git = "neanias/everforest-nvim"
rev = "135cc21a45756e688dd1a3cbeb1c80a04b569b46"
branch = "main"

[plugins."fizz.nvim"]
git = "sebasruiz09/fizz.nvim"
rev = "82303f9135ec371623858a6c2cb60cec2ff59027"
branch = "main"

# ╭─────────────────────────────────────────────╮
# │ Lua port of the most famous vim colorscheme │
# ╰─────────────────────────────────────────────╯
[plugins."gruvbox.nvim"]
name = "gruvbox"
version = "2.0.0"

[plugins."kanagawa.nvim"]
git = "rebelot/kanagawa.nvim"
rev = "cc3b68b08e6a0cb6e6bf9944932940091e49bb83"
branch = "master"

[plugins.materialbox]
git = "mkarmona/materialbox"
rev = "2061e4fcd98555147e849061c1dccac09c972349"
branch = "master"

[plugins."modus-themes.nvim"]
git = "miikanissi/modus-themes.nvim"
rev = "v1.4.1"

[plugins."newpaper.nvim"]
git = "yorik1984/newpaper.nvim"
rev = "07357256a29d9e4bd694dd81e6c1754695890ec6"
branch = "main"

# ╭────────────────────────────────────────────────────────────────────────╮
# │ 🦊A highly customizable theme for vim and neovim with support for lsp, │
# │ treesitter and a variety of plugins.                                   │
# ╰────────────────────────────────────────────────────────────────────────╯
[plugins."nightfox.nvim"]
name = "nightfox"
version = "3.10.0"

[plugins."noctis.nvim"]
git = "talha-akram/noctis.nvim"
rev = "a1b31827dec585d6bb35292f97b8951712ed9312"
branch = "main"

# Dark: Pretty average; not bad.
# Light: Pretty good! Enough contrast and color to make it usable.
# Comments: With there was inactive pane dimming.
[plugins."okcolors.nvim"]
git = "e-q/okcolors.nvim"
rev = "v2.0"

# ╭─────────────────────────────────────────────────────────╮
# │ High Contrast & Vivid Color Scheme based on Monokai Pro │
# ╰─────────────────────────────────────────────────────────╯
[plugins.sonokai]
git = "sainnhe/sonokai"
rev = "v0.3.3"

# I got this for its light colorscheme ("day"), but it's a little on the blue
# side; not sure if I like it for that.
"tokyonight.nvim" = "4.11.0"

[plugins.vim-paper]
git = "yorickpeterse/vim-paper"
rev = "d8decc44569aec6247bae54d971e658bb8108399"
branch = "main"

[plugins.vim-colors-paramount]
git = "owickstrom/vim-colors-paramount"
rev = "a5601d36fb6932e8d1a6f8b37b179a99b1456798"
branch = "master"
