# ╭─────────╮
# │ General │
# ╰─────────╯
import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/keyboard.toml",
]

# working_directory = "~/Development"
live_config_reload = true

# ╭─────╮
# │ Env │
# ╰─────╯
# [env]
# TERM = "xterm-256color"

# ╭────────╮
# │ Window │
# ╰────────╯
[window]
startup_mode = "Fullscreen"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2

# ╭───────────╮
# │ Scrolling │
# ╰───────────╯
[scrolling]
history = 10000
multiplier = 3

# ╭──────╮
# │ Font │
# ╰──────╯
[font]
size = 13.0

[font.normal]
family = "MonoLisa"

# ╭──────╮
# │ Bell │
# ╰──────╯
[bell]
animation = "EaseOutExpo"
duration = 0

# ╭───────────╮
# │ Selection │
# ╰───────────╯
[selection]
# semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

# ╭────────╮
# │ Cursor │
# ╰────────╯
[cursor]

[cursor.style]
blinking = "On"

[cursor.vi_mode_style]
shape = "Beam"
blinking = "On"

# ╭──────────╮
# │ Terminal │
# ╰──────────╯


# ╭───────╮
# │ Mouse │
# ╰───────╯
[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

# ╭───────╮
# │ Hints │
# ╰───────╯

# ╭───────╮
# │ Debug │
# ╰───────╯
# [debug]
# render_timer = false
