
# ╭─────╮
# │ Env │
# ╰─────╯
# [env]
# TERM = "xterm-256color"

# ╭────────╮
# │ Window │
# ╰────────╯
[window]
startup_mode = "Fullscreen"

# [window.dimensions]
# columns = 80
# lines = 24
# Note: Commented out to allow fullscreen mode to use full screen size

[window.padding]
x = 2
y = 2

# ╭───────────╮
# │ Scrolling │
# ╰───────────╯
[scrolling]
history = 10000
multiplier = 3

# ╭──────╮
# │ Font │
# ╰──────╯
[font]
size = 13.0

[font.normal]
family = "MonoLisa"
# Fallback fonts in case MonoLisa is not available
# family = "JetBrains Mono"
# family = "Fira Code"
# family = "SF Mono"
# family = "Monaco"

# ╭──────╮
# │ Bell │
# ╰──────╯
[bell]
animation = "EaseOutExpo"
duration = 100
# Set to 0 to disable bell entirely

# ╭───────────╮
# │ Selection │
# ╰───────────╯
[selection]
# semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

# ╭────────╮
# │ Cursor │
# ╰────────╯
[cursor]

[cursor.style]
blinking = "On"

[cursor.vi_mode_style]
shape = "Beam"
blinking = "On"

# ╭──────────╮
# │ Terminal │
# ╰──────────╯


# ╭───────╮
# │ Mouse │
# ╰───────╯
[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[general]

# working_directory = "~/Development"
live_config_reload = true
# ╭─────────╮
# │ General │
# ╰─────────╯
import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/keyboard.toml",
]

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

# ╭───────╮
# │ Hints │
# ╰───────╯

# ╭───────╮
# │ Debug │
# ╰───────╯
# [debug]
# render_timer = false
