import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/keyboard.toml",
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "MonoLisaCustom Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MonoLisaCustom Nerd Font"
style = "Regular Italic"

[font.normal]
family = "MonoLisaCustom Nerd Font"
style = "Regular Italic"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2
