# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
import = ["rocks/config.toml", "rocks/colorschemes.toml"]

[rocks]

[config]
colorscheme = "kanagawa"

# NOTES:
# - If the plugin name contains a dot then you must add quotes to the key name!
# - Non-git plugins need to come before git-based plugins, otherwise Rocks will not recognize the rocks ones.
[plugins]
"rocks.nvim" = "2.45.0"
"rocks-config.nvim" = "3.1.1"
"rocks-git.nvim" = "2.5.3"
"rocks-treesitter.nvim" = "1.3.0"

# ╭───────────╮
# │ Core deps │
# ╰───────────╯
"comment-box.nvim" = "1.0.2"
"gitsigns.nvim" = "1.0.2"
"lualine.nvim" = "scm"
"which-key.nvim" = { version = "3.17.0", config = "plugins.which_key" }
nvim-lspconfig = "2.3.0"
nvim-web-devicons = "0.100"

# ╭──────────────────────────────╮
# │ Dependencies                 │
# │ (I don't use these directly) │
# ╰──────────────────────────────╯
"plenary.nvim" = "scm"
"nui.nvim" = "0.4.0"

#### Haven't re-evaluated these

"aerial.nvim" = "2.5.0"
"dirbuf.nvim" = "scm"
"fidget.nvim" = "1.6.0"
"mason-lspconfig.nvim" = "2.0.0"
"mason.nvim" = "2.0.0"
"mini.nvim" = "0.16.0"
"neodev.nvim" = "3.0.0"
"schemastore.nvim" = "0.2.0"
"snacks.nvim" = "2.22.0"
"telescope-ui-select.nvim" = "scm"
"telescope.nvim" = "scm"
"todo-comments.nvim" = "1.4.0"
"tokyonight.nvim" = "4.11.0"
"trouble.nvim" = "3.7.1"
"ts-comments.nvim" = "1.5.0"
"yazi.nvim" = "11.5.1"
neogen = "2.20.0"
neotest = "5.8.0"
nvim-nio = "1.10.1"
rustaceanvim = "6.3.0"
tabular = "0.4"
tree-sitter-rust = "0.0.50"
tree-sitter-just = "0.0.37"
tree-sitter-jsonc = "0.0.29"
tree-sitter-toml = "0.0.31"
tree-sitter-yaml = "0.0.36"
tree-sitter-ruby = "0.0.35"
tree-sitter-gitignore = "0.0.29"
tree-sitter-fish = "0.0.30"
tree-sitter-python = "0.0.46"
tree-sitter-git_rebase = "0.0.29"
tree-sitter-bash = "0.0.43"
tree-sitter-ini = "0.0.32"
tree-sitter-properties = "0.0.31"
tree-sitter-starlark = "0.0.31"

################################################################
# Start git-based plugins
################################################################
[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"
rev = "a6d0127a53d39b9fc2af75bd169d288166118aec"
branch = "master"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"
rev = "1f08ed60cafc8f6168b72b80be2b2ea149813e55"
branch = "main"
build = "make"

[plugins."crates.nvim"]
git = "Saecki/crates.nvim"
rev = "v0.7.1"

#############################################

[plugins."open.nvim"]
git = "ofirgall/open.nvim"
rev = "1cabf5fc2c0d59d6273c932546d5465104ad278f"
branch = "master"

[plugins."open-jira.nvim"]
git = "ofirgall/open-jira.nvim"
rev = "dcbe121d675df64f93aa0e50f32c86a1d7439e28"
branch = "master"

[plugins.vim-exchange]
git = "tommcdo/vim-exchange"
rev = "d6c1e9790bcb8df27c483a37167459bbebe0112e"
branch = "master"

[plugins.vim-surround]
git = "tpope/vim-surround"
rev = "v2.2"

[plugins.delimitmate]
git = "raimondi/delimitmate"
rev = "2.7"

[plugins.vim-endwise]
git = "tpope/vim-endwise"
rev = "v1.3"

[plugins.vim-casetrate]
git = "idanarye/vim-casetrate"
rev = "v1.1.0"

[plugins.vim-troll-stopper]
git = "vim-utils/vim-troll-stopper"
rev = "24a9db129cd2e3aa2dcd79742b6cb82a53afef6c"
branch = "master"

#######

[plugins.nvim-hlslens]
git = "kevinhwang91/nvim-hlslens"
rev = "v1.1.0"

[plugins.vim-eunuch]
git = "tpope/vim-eunuch"
rev = "v1.3"

[plugins."bufonly.vim"]
git = "vim-scripts/bufonly.vim"
rev = "0.1"

# [plugins.terminus]
# git = "wincent/terminus"
# branch = "main"

[plugins."quickfix-reflector.vim"]
git = "stefandtw/quickfix-reflector.vim"
rev = "v0.1"

[plugins."lazygit.nvim"]
git = "kdheepak/lazygit.nvim"
rev = "b9eae3badab982e71abab96d3ee1d258f0c07961"
branch = "main"

[plugins."lspkind.nvim"]
git = "onsails/lspkind.nvim"
rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6"
branch = "master"

[plugins.nvim-lint]
git = "mfussenegger/nvim-lint"
rev = "93b8040115c9114dac1047311763bef275e752dc"
branch = "master"

[plugins."fixcursorhold.nvim"]
git = "antoinemadec/fixcursorhold.nvim"
rev = "1900f89dc17c603eec29960f57c00bd9ae696495"
branch = "master"

[plugins.nvim-nonicons]
git = "ya2s/nvim-nonicons"
rev = "ceda07dc7339f35444b5f4c4016f76a9eb42ac16"
branch = "main"

# [plugins.nvim-treesitter-textsubjects]
# git = "rrethy/nvim-treesitter-textsubjects"
# rev = "abcbb0e537c9c24800b03b9ca33bee5806604629"
# branch = "master"

[plugins.treesj]
git = "wansmer/treesj"
rev = "f4049f8ba2177e7c5c03fb9e34d4e039c685d744"
branch = "main"

[plugins."splitjoin.vim"]
git = "andrewradev/splitjoin.vim"
rev = "v1.2.0"

[plugins.vim-commentary]
git = "tpope/vim-commentary"
rev = "v1.3"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2"

[plugins.vim-matchup]
git = "andymass/vim-matchup"
rev = "v0.7.3"

[plugins.vim-dispatch]
git = "tpope/vim-dispatch"
rev = "v1.8"

# ╭────────────────────────────────╮
# │ A solid language pack for Vim. │
# ╰────────────────────────────────╯
[plugins."clangd_extensions.nvim"]
git = "p00f/clangd_extensions.nvim"
rev = "db28f29be928d18cbfb86fbfb9f83f584f658feb"
branch = "main"

[plugins."filetype.nvim"]
git = "nathom/filetype.nvim"
rev = "v0.4"

[plugins.vim-polyglot]
git = "sheerun/vim-polyglot"
rev = "v4.17.1"

[plugins."dockerfile.vim"]
git = "ekalinin/dockerfile.vim"
rev = "2a31e6bcea5977209c05c728c4253d82fd873c82"
branch = "master"

[plugins."committia.vim"]
git = "rhysd/committia.vim"
rev = "c8c0f255e8090ed90dd9d5dd2e8672994f8e3671"
branch = "master"

[plugins.emmet-vim]
git = "mattn/emmet-vim"
rev = "6c511a8d7d2863066f32e25543e2bb99d505172c"
branch = "master"

# ╭───────────────────────────╮
# │ Ruby on Rails power tools │
# ╰───────────────────────────╯
[plugins.vim-rails]
git = "tpope/vim-rails"
rev = "v5.4"

# ╭───────────────────────────────────────╮
# │ It's like rails.vim without the rails │
# ╰───────────────────────────────────────╯
[plugins.vim-rake]
git = "tpope/vim-rake"
rev = "v2.0"

[plugins.vim-projectionist]
git = "tpope/vim-projectionist"
rev = "v1.3"

[plugins.vim-rbs]
git = "turboladen/vim-rbs"
rev = "ef7fe0428dc08100c7efca4c75779d9ffbb40032"
branch = "main"

# ╭───────────────────────────────────────────────────────────────────────────╮
# │ Restores `FocusGained` and `FocusLost` autocommand events work when using │
# │ vim inside Tmux.                                                          │
# ╰───────────────────────────────────────────────────────────────────────────╯
# [plugins.vim-tmux-focus-events]
# git = "tmux-plugins/vim-tmux-focus-events"
# rev = "v1.0.0"

[plugins.vim-yaml]
git = "stephpy/vim-yaml"
rev = "dce19542d5ec1663183b0f6844ec663b5d1f3d24"
branch = "master"

[plugins."codecompanion.nvim"]
git = "olimorris/codecompanion.nvim"
rev = "v16.1.0"

# ╭─────────────────────────────────────────────────────────╮
# │ lsp_lines is a simple neovim plugin that renders        │
# │ diagnostics using virtual lines on top of the real      │
# │ line of code.                                           │
# ╰─────────────────────────────────────────────────────────╯
[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0"

# ╭───────────────────────────────────────────────────────────╮
# │ Use RipGrep in Vim and display results in a quickfix list │
# ╰───────────────────────────────────────────────────────────╯
[plugins.vim-ripgrep]
git = "jremmen/vim-ripgrep"
rev = "v1.0.3"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v1.3.1"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"
rev = "efff286dd74c22f731cdec26a70b46e5b203c619"

[plugins."colorful-menu.nvim"]
git = "xzbdmw/colorful-menu.nvim"
rev = "f80feb8a6706f965321aff24d0ed3849f02a7f77"

[plugins."peek.nvim"]
git = "toppair/peek.nvim"
rev = "5820d937d5414baea5f586dc2a3d912a74636e5b"
build = "deno task --quiet build:fast"

[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"
rev = "cf6cb4f3d7f2729263fc2130de609ff5af22702a"

[plugins."copilotchat.nvim"]
git = "copilotc-nvim/copilotchat.nvim"
rev = "v3.12.0"
build = "make tiktoken"

#          ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#          ┃                         BUNDLES                          ┃
#          ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ╭──────────────╮
# │ Bundle: `ai` │
# ╰──────────────╯
[bundles.ai]
items = ["codecompanion.nvim", "copilotchat.nvim", "copilot.lua"]

# ╭──────────────────╮
# │ Bundle: `coding` │
# ╰──────────────────╯
[bundles.coding]
items = [
  "blink.cmp",
  "friendly-snippets",
  "colorful-menu.nvim",
  "neogen",
  "ts-comments.nvim",
]

# ╭──────────────────╮
# │ Bundle: `editor` │
# ╰──────────────────╯
[bundles.editor]
items = [
  "aerial.nvim",
  "delimitmate",
  "dirbuf.nvim",
  "gitsigns.nvim",
  "nvim-hlslens",
  "tabular",
  "todo-comments.nvim",
  "treesj",
  "trouble.nvim",
  "vim-casetrate",
  "vim-endwise",
  "vim-exchange",
  "vim-ripgrep",
  "vim-surround",
  "vim-troll-stopper",
  "which-key.nvim",
]

# ╭───────────────────╮
# │ Bundle: telescope │
# ╰───────────────────╯
[bundles.telescope]
items = [
  "telescope.nvim",
  "telescope-symbols.nvim",
  "telescope-ui-select.nvim",
  "telescope-fzf-native.nvim",
]

# ╭──────────────────────╮
# │ Bundle: colorschemes │
# ╰──────────────────────╯
[bundles.colorschemes]
items = [
  "balance-theme.nvim",
  "bamboo.nvim",
  "caret.nvim",
  "deepwhite.nvim",
  "everforest-nvim",
  "fizz.nvim",
  "gruvbox.nvim",
  "kanagawa.nvim",
  "materialbox",
  "modus-themes.nvim",
  "newpaper.nvim",
  "nightfox.nvim",
  "noctis.nvim",
  "okcolors.nvim",
  "sonokai",
  "tokyonight.nvim",
  "vim-colors-paramount",
  "vim-paper",
]

# ╭──────────────────╮
# │ Bundle: nvim_cmp │
# ╰──────────────────╯
# [bundles.nvim_cmp]
# items = [
#   "nvim-cmp",
#   "nvim-snippy",
#   "cmp-buffer",
#   "cmp-cmdline",
#   "cmp-nvim-lsp",
#   "cmp-nvim-lsp-signature-help",
#   "cmp-nvim-lua",
#   "cmp-path",
#   "cmp-rg",
# ]

# ╭─────────────────╮
# │ Bundle: `utils` │
# ╰─────────────────╯
[bundles.utils]
items = ["open.nvim", "open-jira.nvim", "vim-dispatch"]

# ╭──────────────────────╮
# │ Bundle: `treesitter` │
# ╰──────────────────────╯
# [bundles.treesitter]
# items = ["nvim-treesitter", "nvim-treesitter-textsubjects", "vim-matchup"]

# ╭───────────────╮
# │ Bundle: `lsp` │
# ╰───────────────╯
[bundles.lsp]
items = [
  "clangd_extensions.nvim",
  "emmet-vim",
  "lsp_lines.nvim",
  "lspkind.nvim",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-lspconfig",
]

# ╭────────────────╮
# │ Bundle: `lang` │
# ╰────────────────╯
[bundles.lang]
items = [
  "committia.vim",
  "crates.nvim",
  "dockerfile.vim",
  "filetype.nvim",
  "peek.nvim",
  "rustaceanvim",
  "vim-polyglot",
  "vim-rails",
  "vim-rake",
  "vim-rbs",
]


# ╭──────────────╮
# │ Bundle: `ui` │
# ╰──────────────╯
[bundles.ui]
items = ["fidget.nvim", "nvim-nonicons", "lualine.nvim", "nui.nvim"]

#          ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#          ┃                    TREESITTER CONFIG                     ┃
#          ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
[treesitter]
auto_highlight = "all"
auto_install = "prompt"
